/*
Operadores Lógicos
&& -> AND -> E // TODAS AS EXPRESSÕES PRECISAM SER VERDADEIRAS PARA RETORNAR TRUE
| | -> OR -> OU // SE UMA RETORNAR FOR TRUE ELE RETORNA TRUE SE TODAS FOREM FALSE ELE RETORNA FALSE
! -> NOT -> NÃO // ELE NEGA UMA EXPRESSÃO (!FALSE RETORNA TRUE !TRUE RETORNA FALSE) é possivel escalonar com !! algumas vezes
*/
